# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for box to differ boxes with same plant', max_length=30, null=True)),
                ('key', models.CharField(help_text='Security key', max_length=10)),
                ('registered', models.BooleanField(default=False, help_text='Displays if the box is registered')),
            ],
        ),
        migrations.CreateModel(
            name='CareMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering_start_time', models.IntegerField(help_text='Time to start watering plant')),
                ('watering_volume', models.IntegerField(help_text='Volume of water to watering plant')),
                ('watering_frequency', models.CharField(help_text='Care frequency', max_length=5)),
                ('illumination_start_time', models.IntegerField(help_text='Time to start illumination')),
                ('illumination_end_time', models.IntegerField(help_text='Time to end illumination')),
                ('illumination_frequency', models.CharField(help_text='Care frequency', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plant name', max_length=30, null=True, unique=True)),
                ('care', models.ForeignKey(help_text='Plant default care method', null=True, on_delete=django.db.models.deletion.CASCADE, to='box.CareMethod')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='care',
            field=models.ForeignKey(help_text='Plant custom care method', null=True, on_delete=django.db.models.deletion.CASCADE, to='box.CareMethod'),
        ),
        migrations.AddField(
            model_name='box',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User-owner of box', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='plant',
            field=models.ForeignKey(blank=True, help_text='Plant name', null=True, on_delete=django.db.models.deletion.CASCADE, to='box.Plant'),
        ),
    ]
