# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_plant_care'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='care',
            field=models.ForeignKey(blank=True, help_text='Plant default care method', null=True, on_delete=django.db.models.deletion.CASCADE, to='box.CareMethod'),
        ),
    ]
