# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0006_auto_20170511_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='caremethod',
            name='name',
            field=models.CharField(help_text='Name for care method to differ them on admin', max_length=20, null=True),
        ),
    ]
