# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0007_caremethod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illumination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for illumination object to differ them on admin', max_length=30)),
                ('illumination_start_time', models.IntegerField(help_text='Time to start illumination')),
                ('illumination_end_time', models.IntegerField(help_text='Time to end illumination')),
                ('illumination_frequency', models.CharField(help_text='Care frequency', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for watering object to differ them on admin', max_length=30)),
                ('watering_start_time', models.IntegerField(help_text='Time to start watering plant')),
                ('watering_volume', models.IntegerField(help_text='Volume of water to watering plant')),
                ('watering_frequency', models.CharField(help_text='Care frequency', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='caremethod',
            name='illumination_end_time',
        ),
        migrations.RemoveField(
            model_name='caremethod',
            name='illumination_frequency',
        ),
        migrations.RemoveField(
            model_name='caremethod',
            name='illumination_start_time',
        ),
        migrations.RemoveField(
            model_name='caremethod',
            name='watering_frequency',
        ),
        migrations.RemoveField(
            model_name='caremethod',
            name='watering_start_time',
        ),
        migrations.RemoveField(
            model_name='caremethod',
            name='watering_volume',
        ),
        migrations.AddField(
            model_name='watering',
            name='care_method',
            field=models.ForeignKey(help_text='Pointer to care method watering belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='box.CareMethod'),
        ),
        migrations.AddField(
            model_name='illumination',
            name='care_method',
            field=models.ForeignKey(help_text='Pointer to care method watering belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='box.CareMethod'),
        ),
    ]
