# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0009_auto_20170511_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='caremethod',
            name='default',
            field=models.BooleanField(default=True, help_text='Flag is care method default or custom'),
        ),
    ]
