# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0010_caremethod_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caremethod',
            name='default',
        ),
        migrations.AddField(
            model_name='caremethod',
            name='illumination_default',
            field=models.BooleanField(default=True, help_text='Flag is illumination default or custom'),
        ),
        migrations.AddField(
            model_name='caremethod',
            name='watering_default',
            field=models.BooleanField(default=True, help_text='Flag is watering default or custom'),
        ),
    ]
