# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0011_auto_20170511_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illumination',
            old_name='illumination_end_time',
            new_name='illumination_duration_time',
        ),
    ]
