# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0012_auto_20170511_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caremethod',
            old_name='illumination_default',
            new_name='is_illumination_default',
        ),
        migrations.RenameField(
            model_name='caremethod',
            old_name='watering_default',
            new_name='is_watering_default',
        ),
    ]
