# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0013_auto_20170512_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(blank=True, default='unregistered', help_text='Name for box to differ boxes with same plant', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='caremethod',
            name='name',
            field=models.CharField(default='unnamed', help_text='Name for care method to differ them on admin', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='illumination',
            name='name',
            field=models.CharField(default='unnamed', help_text='Name for illumination object to differ them on admin', max_length=30),
        ),
        migrations.AlterField(
            model_name='watering',
            name='name',
            field=models.CharField(default='unnamed', help_text='Name for watering object to differ them on admin', max_length=30),
        ),
    ]
