# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0015_auto_20170512_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='status',
            field=models.BooleanField(default=False, help_text='Box connection status'),
        ),
    ]
